spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/yeshan"
    username: "root"
    password: "my-secret-pw"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

server:
  port: 33333

logging:
  level:
    root: info

